// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1602432713);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1602432886);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1602435953);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1602432473);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1602432593);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1602433126);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1602433006);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2189);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1602432323);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{094e9b38-55bd-4019-8fef-f825049548f0}");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1602436817811");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1602438603811");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1602436755280");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1602440355280");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.region", "IE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200622191537");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1602432858");
user_pref("browser.slowStartup.averageTime", 5022);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200622191537");
user_pref("browser.startup.homepage_override.mstone", "68.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1602432857);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.10.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 09 Oct 2020 14:54:21 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1602432713);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200622191537");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f09e8f5a-d763-4e86-b660-3d02754a2b61\",\"fxmonitor@mozilla.org\":\"570f7eb9-f3d0-40f3-9321-3aba9e428f3e\",\"screenshots@mozilla.org\":\"0b2f1997-5100-4533-ae61-3a9b898ba8a9\",\"webcompat-reporter@mozilla.org\":\"e3ef46b9-471a-4999-b040-85a54358490e\",\"webcompat@mozilla.org\":\"2fc2c9d2-62f1-4719-9210-999ad4772329\",\"default-theme@mozilla.org\":\"ba92013a-5471-477a-aec8-11c0e3cd1742\",\"google@search.mozilla.org\":\"0706c416-058d-4989-a1e2-1f7d1625b6b1\",\"amazondotcom@search.mozilla.org\":\"a1727d9e-a3f3-49b3-97ce-b6fda921fe86\",\"bing@search.mozilla.org\":\"c81605db-3429-417a-9602-f3f4ef0cfa27\",\"ddg@search.mozilla.org\":\"81ca3368-b947-4975-b140-f69814cc0761\",\"ebay@search.mozilla.org\":\"648acf61-5943-4c7f-869a-be2a2019e63b\",\"twitter@search.mozilla.org\":\"2cd31bf9-0d87-4af8-b427-2a97e3350bdf\",\"wikipedia@search.mozilla.org\":\"b3ca2042-291a-4927-ad44-bdf58efffaa8\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1602436045);
user_pref("media.gmp-manager.buildID", "20200622191537");
user_pref("media.gmp-manager.lastCheck", 1602432361);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1602436045);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "995b884e-3c78-457f-af34-63ebcb6c8032");
user_pref("security.sandbox.plugin.tempDirSuffix", "e93e94eb-7f46-487d-a4ae-c6e23ae62c29");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1602436045);
user_pref("toolkit.startup.last_success", 1602432854);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200622191537");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
